repos:
- repo: https://github.com/arenadotio/pre-commit-ocamlformat
  rev: 0439858f79b3bcb49e757278eb1312e212d7dd4f
  hooks:
    - id: ocamlformat
      exclude: "^vendor/"
- repo: local
  hooks:
    - id: run-tests
      name: Run unit tests
      entry: ./unittest.sh
      language: script
      types: [directory]
      always_run: true