env_name: ASTEnv
seed: 1
cuda: True
cuda_deterministic: False
num_processes: 8
num_steps: 128
log_interval: 1
eval: False
eval_interval: 1000
save_interval: 100
num_env_steps: 1.0e+8
use_linear_lr_decay: True
env: 
  max_episode_steps: 1
  perturbation: 0
  assignment_dir: /RL_env/data/more_assertions_1_4_int_0_4
  num_assignments: 9
  code_per_assignment:
    - 8
    - 17
    - 15
    - 15
    - 19
    - 23
    - 21
    - 22
    - 20
  cursor_start_pos:
    - 0
    - 2
    - 1
    - 4
    - 4
    - 3
    - 3
    - 1 
    - 2
eval: 
  perturbation: 0
  assignment_dir: /RL_env/data/more_assertions_1_4_int_0_4_test
  num_assignments: 9
  code_per_assignment:
    - 2
    - 5
    - 3
    - 4
    - 6
    - 8
    - 6
    - 3 
    - 3
  cursor_start_pos:
    - 0
    - 2
    - 1
    - 4
    - 4
    - 3
    - 3
    - 1 
    - 2
base: 
  hidden_size: 128
  num_layers: [11, 12, 13, 14]
  embedding_size: 100
  cursor: True
ppo:
  lr: [5.0e-5, 1.0e-5, 5.0e-6, 1.0e-6]
  eps: 1.0e-5
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  ppo_epoch: 4
  num_mini_batch: 4
  clip_param: 0.1
  entropy_coef: 0.01
return:
  gamma: 0.99
  use_gae: True
  gae_lambda: 0.95
  use_proper_time_limits: False
