env_name: ASTEnv
seed: 1
cuda: True
project_name: "assistant_rl"
cuda_deterministic: True
num_processes: 8  
num_steps: 128
log_interval: 1   
eval_interval: 100 # Eval is just target # Skips eval step. (used to be 1000)
save_interval: 1000
num_env_steps: 1.0e+7
use_linear_lr_decay: True
resume_carryover:  [ 'seed', 'env', 'eval', 'base', 'ppo', 'make_tests','return' ]
env:
  get_from: data/auto_curricula/two_vars/param_snippet.yaml
eval:
  get_from: data/auto_curricula/two_vars/param_snippet.yaml
base: 
  hidden_size: 400
  num_layers: 10
  embedding_size: 250
  heads: 16
  use_qkv: False
  gnn_type: GATv2
ppo:
  lr: 1.0e-5   
  eps: 1.0e-5
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  ppo_epoch: 4
  num_mini_batch: 4
  clip_param: 0.1
  entropy_coef: 0.015
make_tests: 
  # command: echo "Using cached generated tests at  /RL_env/save/data/auto_curricula/four_var/curriculum"
  command: python3 scripts/gen_template_funcs.py
  args:
    base: ['3', 'data/auto_curricula/two_vars','-c']
    # test_split: 0.8
    seed: 26 # from my birthday why not 
    mns_correction: 1.3
return:
  gamma: 0.99
  use_gae: True
  gae_lambda: 0.95
  use_proper_time_limits: False
