env_name: ASTEnv
seed: 1
cuda: True
project_name: "assistant_rl"
cuda_deterministic: True
num_processes: 8  
num_steps: 128
log_interval: 1   
eval_interval: 0 # Eval is just target # Skips eval step. (used to be 1000)
save_interval: 1000
num_env_steps: 1.0e+7
use_linear_lr_decay: True
resume_carryover:  [ 'seed', 'env', 'eval', 'base', 'ppo', 'make_tests','return' ]
env:
  assignment_dir: data/xor
  code_per_assignment:
  - 3
  - 4
  - 3
  - 1
  - 1
  - 1
  - 1
  - 1
  cursor_start_pos:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  done_action: true
  max_episode_steps: 22
  num_assignments: 8
  perturbation: 0
# eval:
#   get_from: data/auto_curricula/two_vars/param_snippet.yaml
base: 
  hidden_size: 64
  num_layers: 1
  embedding_size: 128
  node_dim: 64
  edge_dim: 16
  heads: 2
  use_qkv: False
ppo:
  lr: 1.0e-5   
  eps: 1.0e-5
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  ppo_epoch: 4
  num_mini_batch: 4
  clip_param: 0.1
  entropy_coef: 0.015
make_tests: 
  # command: echo "Using cached generated tests at  /RL_env/save/data/auto_curricula/four_var/curriculum"
  command: python3 scripts/gen_template_funcs.py
  args:
    base: ['2', 'data/auto_curricula/two_vars','-c']
return:
  gamma: 0.99
  use_gae: True
  gae_lambda: 0.95
  use_proper_time_limits: False
