env_name: ASTEnv
seed: 1
cuda: True
cuda_deterministic: False
num_processes: 8
num_steps: 128
log_interval: 1
eval: False
eval_interval: 1000
save_interval: 100
num_env_steps: 1.0e+8
use_linear_lr_decay: True
env: 
  max_episode_steps: 1
  perturbation: 0
  assignment_dir: data/auto
  num_assignments: 1
  code_per_assignment: [100]
  cursor_start_pos: [6]
  # num_assignments: 1
  # code_per_assignment: [9]
  # cursor_start_pos: [6]
eval: 
  perturbation: 0
  assignment_dir: data/tests
  num_assignments: 1
  code_per_assignment: [10]
  cursor_start_pos: [6]
base: 
  hidden_size: 128
  num_layers: 11
  embedding_size: 100
  cursor: True
ppo:
  lr: 1.0e-5
  eps: 1.0e-5
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  ppo_epoch: 4
  num_mini_batch: 4
  clip_param: 0.1
  entropy_coef: 0.01
return:
  gamma: 0.99
  use_gae: True
  gae_lambda: 0.95
  use_proper_time_limits: False
