env_name: ASTEnv
seed: 1
cuda: True
cuda_deterministic: False
num_processes: 8  
num_steps: 128
log_interval: 1   
eval_interval: 1000
save_interval: 100
num_env_steps: 1.0e+8
use_linear_lr_decay: True
env: 
  max_episode_steps: 15
  perturbation: 0
  assignment_dir: data/generated_tests/binary_funcs_subsets/no_moves/train # TODO 
  num_assignments: 1  
  code_per_assignment: [5] #TODO
  cursor_start_pos: [0] 
  # num_assignments: 1
  # code_per_assignment: [9]
  # cursor_start_pos: [6]
eval: 
  perturbation: 0
  # max_episode_steps: 15
  assignment_dir: data/generated_tests/binary_funcs_subsets/no_moves/test
  num_assignments: 1 #TODO 
  code_per_assignment: [0] #TODO
  cursor_start_pos: [0] 
base: 
  hidden_size: 128
  num_layers: 15
  embedding_size: 100
  cursor: True
ppo:
  lr: 1.0e-5  # sweep this 
  eps: 1.0e-5  # also sweep this 
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  ppo_epoch: 4
  num_mini_batch: 4
  clip_param: 0.1
  entropy_coef: 0.01
make_tests: 
  command: python3 scripts/Generate_boolean_funcs.py
  args:
    min_n: 2
    max_n: 2
    max_funcs: 500
    test_ratio: 0.0
    shuffle: False
    outdir: data/generated_tests/binary_funcs_subsets/no_moves
    choose_tests: "[[0, 3, 10, 12, 15]]"
    seed: 42 
return:
  gamma: 0.99
  use_gae: True
  gae_lambda: 0.95
  use_proper_time_limits: False
