env_name: ASTEnv
seed: 1
cuda: true
project_name: assistant_rl
cuda_deterministic: true
num_processes: 8
num_steps: 128
log_interval: 1
eval_interval: 0 #1000
save_interval: 1000
num_env_steps: 1.0e+8
use_linear_lr_decay: true
resume_carryover:
  - seed
  - env
  - eval
  - base
  - ppo
  - make_tests
  - return
env:
  get_from1: data/auto_curricula/1_basic/param_snippet.yaml   
  # get_from2: data/auto_curricula/3_basic/param_snippet.yaml    
  ds_ratio: [0.4,0.6]
  perturbation: 0
base: 
  hidden_size: 64
  num_layers: 1
  embedding_size: 128
  node_dim: 64
  edge_dim: 16
  heads: 2
  use_qkv: False
ppo:
    lr: 1.0e-05
    eps: 1.0e-05
    value_loss_coef: 0.5
    max_grad_norm: 0.5
    ppo_epoch: 4
    num_mini_batch: 4
    clip_param: 0.1
    entropy_coef: 0.015
    entropy_coeff_decay: True 
make_tests:
    command: python3 scripts/gen_template_funcs.py
    args:
      base:
      - '1'
      - data/auto_curricula/1_basic
      # - -v 
      mns_correction: 1.6
      curriculum: 
      variations: false  
      permutations: false
      # test_split: 0.5
return:
    gamma: 0.99
    use_gae: true
    gae_lambda: 0.95
    use_proper_time_limits: false
